### ISSUE TITLE
deleteMessage

### ISSUE THREAD

**Issue by ghost** [elbekD/kt-telegram-bot#17]
**Is your feature request related to a problem? Please describe.**
While creating a moderation bot, it would be useful to delete previous welcome messages to keep the group history clean.

**Describe the solution you'd like**
https://core.telegram.org/bots/api#deletemessage
Implementing this API would allow a bot to delete its own historical and potentially lengthy messages.

**Describe alternatives you've considered**
editmessage allows to shorten old messages significantly and makes a good workaround for the moment.

**Comment by elbekD** [comment]
@mimithebrain thnx for issue. checkout version 1.2.1

**Comment by ghost** [comment]
Integrated, unit tests pass, and works great!

Thanks again!
