### ISSUE TITLE
Rename preview in sendMessage to disablePreview

### ISSUE THREAD

**Issue by den-gap** [elbekD/kt-telegram-bot#24]
hi, I tried to disable the web preview in the message and set the preview property to false, but it still appeared and when I saw that the official api has the disable_web_preview property, I realized that I should set it to true. So please rename the property, cause now the behavior is illogical

**Comment by elbekD** [comment]
hi! thank u for suggestion! checkout version 1.3.1

**Comment by den-gap** [comment]
editMessageText same problem

**Comment by elbekD** [comment]
fixed in 1.3.2
