### ISSUE TITLE
Can't access chatID and username in group chat

### ISSUE THREAD

**Issue by moeindev** [elbekD/kt-telegram-bot#27]
In my case, I can't access the chat id and usernames in group chats, it gives me null value

**Comment by elbekD** [comment]
can you please provide more details? code example

**Comment by moeindev** [comment]
for example, if I send a command in a group chat like this: 
`bot.onCommand("/mycommand") {msg,_ ->
            val uName = msg.chat.username
        }`
the usernme will be null but in the Group chats, but in private chats  it's not null!

**Comment by elbekD** [comment]
docs for Chat object says: username - Optional. Username, for private chats, supergroups and channels if available.
username is not available for private groups, so make it public
