### ISSUE TITLE
Create codegen tooling

### ISSUE THREAD

**Issue by elbekD** [elbekD/kt-telegram-bot#41]
Now in order to support changes in API it is necessary to do eye-parsing of changes and then write additional code. It is manual, time consuming and error prone activity. Consider next solutions:
1. Maybe there is some structured file(s) with definitions of the API(like `yaml` or `json` files). If there are then make code generation tool
2. Make code generation tool which will parse `html` file of the [API](https://core.telegram.org/bots/api) page

**Comment by SonicNorg** [comment]
Here `yaml` and `json` TelegramBot API can be found:
https://github.com/sys-001/telegram-bot-api-versions/tree/main/files/openapi/yaml
